### PR TITLE
add linguist-language attribute for twinBASIC

### PR DESCRIPTION
**Pull request by GCuser99**
plus a few very minor consistency edits

### CODE REVIEW

**Comment by GCuser99** [comment]
I'm a VBA hobbyist, not a VB6 developer, which explains my choice without having given the choice much thought. tB claims to be compatible with both. I'm indifferent - it won't matter to me if we use VB6. Maybe that's better since it might be argued that VBA is a subset of VB6? Do you want me to change to VB6 in my PR?

**Comment by GCuser99** [comment]
I just tested the difference - and there is! VB6 uses red for recognized keywords and types. VBA uses red for recognized keywords and blue for types. I prefer the look of VBA but maybe it would be best, like you suggest, to use VB6 since there are probably more VB6'ers currently using tB than VBA'ers. Let me know and I'll make the change to the PR.

This one is VBA:
image

This one is VB6:
image

**Comment by GCuser99** [comment]
Another thing that I just thought of to consider... tB is 64-bit and supports VBA7 types/syntax like LongPtr, LongLong, and PtrSafe. These won't be recognized with VB6, whereas they will using VBA.

**Comment by fafalone** [comment]
I use VB6 because tB is more similar to that, excepting PtrSafe/LongPtr, but as they're functionally the same language I think it comes down to preference. I use VBA for syntax highlighting in readmes.

What is important IMO is to tag repos with tB files with twinbasic in the Topics area of About the repo. GitHub will need to see at least 200 repositories in a language before it qualifies for its own linguist entry, so it makes them easy to find.

**Comment by DecimalTurn** [comment]
> I prefer the look of VBA

I do too. I guess it's time to update the syntax highlighting grammar used by GitHub for VB6 to use VBA's instead of VB.NET's .
I probably should have done it a long time ago, but at least we'll get the nicer highlighting in the next Linguist release.

>  Let me know and I'll make the change to the PR.

@GCuser99 yeah, please edit the PR to use VB6. It's a reasonable default value for now.

**Comment by DecimalTurn** [comment]
> What is important IMO is to tag repos with tB files with twinbasic in the Topics area of About the repo. GitHub will need to see at least 200 repositories in a language before it qualifies for its own linguist entry, so it makes them easy to find.

Looking at recent languages that were added to Linguist and due to the way the new GitHub search works, it seems that the number of files using the extension is the only relevate criteria used to determine if a language is eligible. However, that count has to exclude a few top contributors since they can have "an undue influence on the figures".

**Comment by fafalone** [comment]
I was going by https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md and https://github.com/github-linguist/linguist/issues/5756 in particular:

> at least 2000 files per extension indexed in the last year (the number you see at the top of the search results), unless the extension is expected to only occur once per repo, then 200 files. with a reasonable distribution across unique :user/:repo combinations assessed by manually and randomly clicking through the results.

You all do need to step up your game though so I'm not so heavily dominating the results 😁

**Comment by GCuser99** [comment]
Done!

**Comment by DecimalTurn** [comment]
@GCuser99 Looks good, thanks!

**Pull request merged**
